<?php
/**
 * @file
 * kr_picturemaps.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function kr_picturemaps_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "breakpoints" && $api == "default_breakpoint_group") {
    return array("version" => "1");
  }
  if ($module == "breakpoints" && $api == "default_breakpoints") {
    return array("version" => "1");
  }
  if ($module == "picture" && $api == "default_picture_mapping") {
    return array("version" => "2");
  }
}
